FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04
    MAINTAINER Niranjan Ravichandra <nravic@cedana-linux>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    wget \
    git \
    curl \
    build-essential \
    sudo apt install libssl-dev \
    unzip \
    python3-pip \
    openmpi-bin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH
ENV SHELL=/bin/bash

WORKDIR /app
COPY requirements-compbio.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && rm -rf /root/.cache/pip

COPY cpu_smr/ /app/cpu_smr/
COPY gpu_smr/ /app/gpu_smr/

# Install CMake 3.28.3 from source
RUN <<EOT
    set -eux
    CMAKE_VERSION=3.28.3
    cd /tmp
    curl -fsSL -O https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz
    tar -xzf cmake-${CMAKE_VERSION}.tar.gz
    cd cmake-${CMAKE_VERSION}
    ./bootstrap --prefix=/usr/local
    make -j$(nproc)
    make install
    cd /
    rm -rf /tmp/cmake-${CMAKE_VERSION} /tmp/cmake-${CMAKE_VERSION}.tar.gz
EOT

# Chai-1 model
RUN <<EOT
    set -eux
    cd /app/gpu_smr/compbio/chai-1
    bash ./setup_chai.sh
EOT

# OpenMM model
RUN <<EOT
    set -eux
    cd /app/gpu_smr/compbio/openmm
    bash ./setup_openmm.sh
EOT

# GROMACS build
RUN <<EOT
    set -eux
    cd /app/gpu_smr/compbio/gromacs
    bash ./build_once.sh
EOT

ENTRYPOINT ["/bin/bash", "-c"]
