apiVersion: v1
kind: Pod
metadata:
  generateName: nginx
  namespace: default 
  labels:
    cedana.ai/heartbeat-checkpoint: "60"
    cedana.ai/node-restore: "true"
    cedana.ai/node-interruption-checkpoint: "true"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 1
  restartPolicy: OnFailure
