# test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: vector-add-pod
  labels:
    app: cedana-test
spec:
  runtimeClassName: cedana
  restartPolicy: Never
  containers:
  - name: workload-container
    image: "cedana/cedana-samples:latest"
    command: ["/bin/sh", "-c", "/app/gpu_smr/vector_add"]

    resources: 
      limits: 
        nvidia.com/gpu: 1
