apiVersion: v1
kind: Pod
metadata:
  generateName: counting-
  namespace: default
spec:
  containers:
    - name: counting
      image: cedana/cedana-samples:cpu
      args:
        - -c
        - cpu_smr/counting.sh
