apiVersion: v1
kind: Pod
metadata:
  generateName: tensorflow-example-
  namespace: default
spec:
  runtimeClassName: cedana # required for GPU C/R support (use nvidia for native)
  containers:
    - name: tensorflow-example
      image: cedana/cedana-samples-test:cuda12.4-torch2.7@sha256:550fab02f17d97eb3e788ab2c797cb0c7f1c802346373ae2e42ae3fc53a29033
      command:
        - python3
        - -u
        - gpu_smr/pytorch/training/tensorflow_train.py
