apiVersion: v1
kind: Pod
metadata:
  generateName: cuda-mem-throughput-
  namespace: default
spec:
  runtimeClassName: cedana # required for GPU C/R support (use nvidia for native)
  containers:
    - name: cuda-mem-throughput
      image: cedana/cedana-samples:cuda
      args:
        - -c
        - gpu_smr/mem-throughput-saxpy-loop
      resources:
        limits:
          nvidia.com/gpu: 1
