apiVersion: v1
kind: Pod
metadata:
  generateName: pytorch-train-nn-
  namespace: default
spec:
  runtimeClassName: cedana # required for GPU C/R support (use nvidia for native)
  containers:
    - name: pytorch-train-nn
      image: cedana/cedana-samples:cuda12.4-torch2.5
      command:
        ["python3", "-u", "gpu_smr/pytorch/training/test.py"]
      resources:
        limits:
          nvidia.com/gpu: 1
