apiVersion: v1
kind: Pod
metadata:
  generateName: deepspeed-train-example-
  namespace: default
spec:
  runtimeClassName: cedana # required for GPU C/R support (use nvidia for native)
  containers:
    - name: deepspeed-train
      image: cedana/cedana-samples-test:cuda12.4-torch2.7
      command:
        - deepspeed
        - --num_gpus=1
        - gpu_smr/pytorch/training/deepspeed_train.py
      resources:
        limits:
          nvidia.com/gpu: 1
