apiVersion: v1
kind: Pod
metadata:
  generateName: openmm-simulatepdb-
  namespace: default
spec:
  runtimeClassName: cedana # required for GPU C/R support (use nvidia for native)
  containers:
    - name: openmm-simulatepdb
      image: cedana/cedana-samples:compbio
      command:
        - bash
        - -c
        - /app/gpu_smr/compbio/openmm/openmm_example.sh
      resources:
        limits:
          nvidia.com/gpu: 1
