#!/bin/bash

## kill all cedana first
pgrep cedana | xargs -r sudo kill -TERM

## Mount a shared bucket
s3fs cedana-demo /mnt/s3 -o passwd_file=~/.passwd-s3fs

## Quick script to start daemon on node bootup (manually!)
sudo cedana daemon start &
