apiVersion: v1
kind: Pod
metadata:
  generateName: torch-nccl-hostmem-
  namespace: default
spec:
  runtimeClassName: cedana
  restartPolicy: Never
  containers:
    - name: torch-nccl-hostmem
      image: cedana/cedana-samples:cuda12.8-torch2.7
      command: ["python3"]
      args:
        - /app/gpu_smr/pytorch/nccl_hostmem.py
      resources:
        limits:
          nvidia.com/gpu: 2
