name: PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image: true
      image_name: cedana/cedana-samples-test

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs: build
    secrets: inherit
    with:
      image_name: cedana/cedana-samples-test
      dockerhub: true
      post_summary: true
