name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write
  id-token: write
  pull-requests: write

concurrency:
  group: cedana-samples-release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: runs-on=${{github.run_id}}/runner=4cpu-16g-${{ matrix.arch }}/extras=s3-cache
    strategy:
      fail-fast: false
      matrix:
        cuda_version:
          - 11.8
          - 12.2
          - 12.4
          - 12.8
        torch_version:
          - 2.4
          - 2.5
          - 2.6
        arch:
          - amd64
          - arm64
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          submodules: recursive
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: cedana/cedana-samples

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and generate manifest
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            TORCH_VERSION=${{ matrix.torch_version }}
          context: .
          push: true
          platforms: linux/${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: |
            type=image,name=cedana/cedana-samples,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/${{ matrix.arch }},region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }}
          cache-to: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/${{ matrix.arch }},region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }},mode=max

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.cuda_version }}-${{ matrix.torch_version }}-${{ matrix.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  publish:
    name: Publish (multi-arch)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda_version:
          - 11.8
          - 12.2
          - 12.4
          - 12.8
        torch_version:
          - 2.4
          - 2.5
          - 2.6
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ matrix.cuda_version }}-${{ matrix.torch_version }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cedana/cedana-samples
          tags: |
            type=raw,value=cuda${{ matrix.cuda_version }}-torch${{ matrix.torch_version }}
            type=raw,value=${{ github.ref_name }}-cuda${{ matrix.cuda_version }}-torch${{ matrix.torch_version }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'cedana/cedana-samples@sha256:%s ' *)

      - name: Inspect image
        run: |
          # check if push was successful
          docker buildx imagetools inspect cedana/cedana-samples:${{ steps.meta.outputs.version }}
