name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

concurrency:
  group: release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image: true

  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    needs: build
    secrets: inherit
    with:
      dockerhub: true
      post_summary: true
